swagger: "2.0"
info:
    version: 1.0.1
    title: "{{ packageJson('name') }}"
    description: A sample API
    contact:
        name: Swagger API Team
        email: 'john@boats.io'
        url: https://github.com/johndcarmichael/boats/
    license:
        name: Apache 2.0
        url: https://www.apache.org/licenses/LICENSE-2.0.html

schemes:
    - https
    - http
host: api.example.com

paths:
    $ref: paths/index.yml

basePath: /v1

{{
  inject([{
    toAllOperations: {
      content: {
        tags: [ '{{ autoTag() }}' ],
        operationId: '{{ uniqueOpId() }}'
      }
    }
  }])
}}
